# nome da pipeline
name: Run Basic Testes

# em que momento irá ser executada
on: 
  pull_request:
    branches: [main]

jobs:
  # o que vai ser feito nessa pipeline
  cypress-run:
    # maquina que será executada
    runs-on: ubuntu-latest
    # passo a passo para rodar os testes
    steps:
      # clone do projeto (versão atualizada v4)
      - name: checkout/Clone do projeto
        uses: actions/checkout@v4

      # Execução dos testes e gerenciamento de dependências via action oficial do Cypress
      - name: Cypress run
        uses: cypress-io/github-action@v7
        with:
          record: true
          # Garante que a pasta de relatórios seja limpa/criada corretamente pelo próprio fluxo se necessário
          # E roda os testes
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

      # upload do relatorio mocha (versão atualizada v4)
      - name: upload relatório
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-cypress
          path: cypress/reports/html